<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `v9_category`;");
E_C("CREATE TABLE `v9_category` (
  `catid` smallint(5) unsigned NOT NULL auto_increment,
  `siteid` smallint(5) unsigned NOT NULL default '0',
  `module` varchar(15) NOT NULL,
  `type` tinyint(1) unsigned NOT NULL default '0',
  `modelid` smallint(5) unsigned NOT NULL default '0',
  `parentid` smallint(5) unsigned NOT NULL default '0',
  `arrparentid` varchar(255) NOT NULL,
  `child` tinyint(1) unsigned NOT NULL default '0',
  `arrchildid` mediumtext NOT NULL,
  `catname` varchar(30) NOT NULL,
  `style` varchar(5) NOT NULL,
  `image` varchar(100) NOT NULL,
  `description` mediumtext NOT NULL,
  `parentdir` varchar(100) NOT NULL,
  `catdir` varchar(30) NOT NULL,
  `url` varchar(100) NOT NULL,
  `items` mediumint(8) unsigned NOT NULL default '0',
  `hits` int(10) unsigned NOT NULL default '0',
  `setting` mediumtext NOT NULL,
  `listorder` smallint(5) unsigned NOT NULL default '0',
  `ismenu` tinyint(1) unsigned NOT NULL default '1',
  `sethtml` tinyint(1) unsigned NOT NULL default '0',
  `letter` varchar(30) NOT NULL,
  `usable_type` varchar(255) NOT NULL,
  PRIMARY KEY  (`catid`),
  KEY `module` (`module`,`parentid`,`listorder`,`catid`),
  KEY `siteid` (`siteid`,`type`)
) ENGINE=MyISAM AUTO_INCREMENT=30 DEFAULT CHARSET=utf8");
E_D("replace into `v9_category` values('1','1','content','1','0','0','0','1','1,2,18,4,17,5,3,19','关于双昌','','','','','about','/html/about/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','6','0','0','guanyushuangchang','');");
E_D("replace into `v9_category` values('2','1','content','1','0','1','0,1','0','2','双昌简介','','','','about/','profile','/html/about/profile/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => ''关于我们'',\n  ''meta_keywords'' => ''关于我们'',\n  ''meta_description'' => ''关于我们'',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','1','1','0','shuangchangjianjie','');");
E_D("replace into `v9_category` values('3','1','content','1','0','1','0,1','0','3','联系我们','','','','about/','contactus','/html/about/contactus/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => ''联系方式'',\n  ''meta_keywords'' => ''联系方式'',\n  ''meta_description'' => ''联系方式'',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','6','1','0','lianxiwomen','');");
E_D("replace into `v9_category` values('4','1','content','1','0','1','0,1','0','4','双昌荣誉','','','','about/','honour','/html/about/honour/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => ''版权声明'',\n  ''meta_keywords'' => ''版权声明'',\n  ''meta_description'' => ''版权声明'',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','3','1','0','shuangchangrongyu','');");
E_D("replace into `v9_category` values('5','1','content','1','0','1','0,1','0','5','招贤纳士','','','','about/','hr','/html/about/hr/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','5','1','0','zhaoxiannashi','');");
E_D("replace into `v9_category` values('6','1','content','0','1','0','0','1','6,9,10,11','公司新闻','','','','','news','/html/news/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category_news'',\n  ''list_template'' => ''list_news'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','5','1','0','gongsixinwen','');");
E_D("replace into `v9_category` values('17','1','content','1','0','1','0,1','0','17','服务团队','','','','about/','service','/html/about/service/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','4','1','0','fuwutuandui','');");
E_D("replace into `v9_category` values('7','1','content','0','2','0','0','0','7','下载','','','','','down','http://hy.30ie.com/index.php?m=content&c=index&a=lists&catid=7','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','7','0','0','xiazai','');");
E_D("replace into `v9_category` values('8','1','content','0','3','0','0','0','8','图片','','','','','pps','http://hy.30ie.com/index.php?m=content&c=index&a=lists&catid=8','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','8','0','0','tupian','');");
E_D("replace into `v9_category` values('16','1','content','0','1','0','0','0','16','SEO优化转入','','','','','transferred','/html/transferred/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_transferred'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => ''18'',\n)','3','0','0','seoyouhuazhuanru','');");
E_D("replace into `v9_category` values('9','1','content','0','1','6','0,6','0','9','双昌动态','','','','news/','dynamic','/html/dynamic/','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category_news'',\n  ''list_template'' => ''list_news'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','1','1','0','shuangchangdongtai','');");
E_D("replace into `v9_category` values('10','1','content','0','1','6','0,6','0','10','双昌观点','','','','news/','view','/html/view/','9','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category_news'',\n  ''list_template'' => ''list_news'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','2','1','0','shuangchangguandian','');");
E_D("replace into `v9_category` values('11','1','content','0','1','6','0,6','0','11','建站资讯','','','','news/','website','/html/website/','8','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category_news'',\n  ''list_template'' => ''list_news'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','3','1','0','jianzhanzixun','');");
E_D("replace into `v9_category` values('12','1','content','0','1','0','0','0','12','实用套餐','','','','','package','/html/package/','5','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','5','0','0','shiyongtaocan','');");
E_D("replace into `v9_category` values('13','1','content','0','1','0','0','0','13','SEO案例','','','','','case','http://hy.30ie.com/index.php?m=content&c=index&a=lists&catid=13','6','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_case'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','4','1','0','seoanli','');");
E_D("replace into `v9_category` values('14','1','content','1','0','0','0','0','14','搜索引擎优化','','','','','seo','/html/seo/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_seo'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','1','1','0','sousuoyinqingyouhua','');");
E_D("replace into `v9_category` values('15','1','content','0','1','0','0','1','15,21,22,23,24,25,26,27,28,29','网站建设案例','','','','','sevsite','/html/sevsite/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category_website'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','2','1','0','wangzhanjiansheanli','');");
E_D("replace into `v9_category` values('20','1','content','0','1','0','0','0','20','最新签约客户','','','','','customer','/html/customer/','20','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category_news'',\n  ''list_template'' => ''list_news'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','7','0','0','zuixinqianyuekehu','');");
E_D("replace into `v9_category` values('18','1','content','1','0','1','0,1','0','18','发展历程','','','','about/','history','/html/about/history/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','2','1','0','fazhanlicheng','');");
E_D("replace into `v9_category` values('19','1','content','1','0','1','0,1','0','19','付款方式','','','','about/','payment','/html/about/payment/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''hy30ie'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''31'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','7','1','0','fukuanfangshi','');");
E_D("replace into `v9_category` values('21','1','content','0','1','15','0,15','0','21','餐饮行业','','','','sevsite/','Catering','/html/Catering/','5','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','21','1','0','canyinxingye','');");
E_D("replace into `v9_category` values('22','1','content','0','1','15','0,15','0','22','旅游行业','','','','sevsite/','Travel','/html/Travel/','5','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','22','1','0','lvyouxingye','');");
E_D("replace into `v9_category` values('23','1','content','0','1','15','0,15','0','23','房地产行业','','','','sevsite/','RealEstate','/html/RealEstate/','6','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','23','1','0','fangdichanxingye','');");
E_D("replace into `v9_category` values('24','1','content','0','1','15','0,15','0','24','教育行业','','','','sevsite/','Train','/html/Train/','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','24','1','0','jiaoyuxingye','');");
E_D("replace into `v9_category` values('25','1','content','0','1','15','0,15','0','25','汽车行业','','','','sevsite/','Auto','/html/Auto/','5','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','25','1','0','qichexingye','');");
E_D("replace into `v9_category` values('26','1','content','0','1','15','0,15','0','26','电子产品','','','','sevsite/','Electronic','/html/Electronic/','6','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','26','1','0','dianzichanpin','');");
E_D("replace into `v9_category` values('27','1','content','0','1','15','0,15','0','27','律所行业','','','','sevsite/','LawFirm','/html/LawFirm/','6','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','27','1','0','lvsuoxingye','');");
E_D("replace into `v9_category` values('28','1','content','0','1','15','0,15','0','28','管理咨询','','','','sevsite/','Management','/html/Management/','4','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','28','1','0','guanlizixun','');");
E_D("replace into `v9_category` values('29','1','content','0','1','15','0,15','0','29','服装行业','','','','sevsite/','Clothing','/html/Clothing/','6','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''hy30ie'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_website'',\n  ''show_template'' => ''show_news'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''30'',\n  ''show_ruleid'' => ''18'',\n)','29','1','0','fuzhuangxingye','');");

require("../../inc/footer.php");
?>