<?php
return array (
  'title' => '行业',
  'style' => '2',
  'siteid' => '0',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '娱乐类',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3361,3370,3371,3372,3373,3374,3375,3376,3377,3378,3379,3380,3381,3382,3383,3384,3385,3386,3387,3388',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => 'IT网络',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3362,3389,3390,3391,3392,3393,3394,3395,3396',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '教育人才',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3363,3397,3398,3399,3400,3401,3402',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '医疗医学',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3364,3403,3404,3405,3406',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '百姓生活',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3365,3407,3408,3409,3410,3411,3412,3413,3414,3415,3416,3417,3418,3419',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '经济商贸',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3366,3420,3421,3422,3423,3424,3425',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '行业类',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3367,3426,3427,3428,3429,3430,3431,3432,3433',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '论坛博客',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3368,3434,3435,3436,3437,3438,3439,3440,3441,3442,3443,3444',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '其它类',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3369,3445',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '聊天',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3370',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '体育',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3371',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '文学',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3372',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '图片',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3373',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '交友',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3374',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '图铃',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3375',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '音乐',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3376',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '娱乐综合',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3377',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '游戏',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3378',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '网页游戏',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3379',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '电影',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '军事',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3381',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '娱乐其它',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3382',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '动漫',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3383',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '视频',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3384',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '星相',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3385',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '彩票博彩',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3386',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => 'flash',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '幽默笑话',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => 'IT网络其它',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => 'IT资讯',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '网址导航',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3391',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '下载',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '地方信息港',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '搜索引擎',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '网站制作',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3395',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '电脑软件',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '科普',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '办公文教',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3398',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '教育培训',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '招聘',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3400',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '留学移民',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3401',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3402 => 
    array (
      'linkageid' => '3402',
      'name' => '教育人才其它',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3402',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '医学医药',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3403',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3404 => 
    array (
      'linkageid' => '3404',
      'name' => '两性健康',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3404',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '医疗器械',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3405',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '整形美容',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3406',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3407 => 
    array (
      'linkageid' => '3407',
      'name' => '艺术爱好',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3407',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '旅游',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3408',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '房产',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3409',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3410 => 
    array (
      'linkageid' => '3410',
      'name' => '家居装饰',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3410',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '礼品玩具',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3411',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3412 => 
    array (
      'linkageid' => '3412',
      'name' => '服装服饰',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3412',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3413 => 
    array (
      'linkageid' => '3413',
      'name' => '食品饮食',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3413',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '家电数码',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3414',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '酒店机票预订',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3415',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3416 => 
    array (
      'linkageid' => '3416',
      'name' => '百姓生活其它',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3416',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3417 => 
    array (
      'linkageid' => '3417',
      'name' => '生活/时尚',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3417',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3418 => 
    array (
      'linkageid' => '3418',
      'name' => 'SNS',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3418',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3419 => 
    array (
      'linkageid' => '3419',
      'name' => '汽车',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3419',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3420 => 
    array (
      'linkageid' => '3420',
      'name' => '团购与团购导航',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3420',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3421 => 
    array (
      'linkageid' => '3421',
      'name' => '招商加盟',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3421',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3422 => 
    array (
      'linkageid' => '3422',
      'name' => 'B2C商城',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3422',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3423 => 
    array (
      'linkageid' => '3423',
      'name' => 'B2B商城',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3423',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3424 => 
    array (
      'linkageid' => '3424',
      'name' => '财经证券',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3424',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3425 => 
    array (
      'linkageid' => '3425',
      'name' => '交通物流',
      'style' => '',
      'parentid' => '3366',
      'child' => '0',
      'arrchildid' => '3425',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3426 => 
    array (
      'linkageid' => '3426',
      'name' => '企业',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3426',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3427 => 
    array (
      'linkageid' => '3427',
      'name' => '机械设备',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3427',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3428 => 
    array (
      'linkageid' => '3428',
      'name' => '电子电工',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3428',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3429 => 
    array (
      'linkageid' => '3429',
      'name' => '化工能源',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3429',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3430 => 
    array (
      'linkageid' => '3430',
      'name' => '冶金矿产',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3430',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3431 => 
    array (
      'linkageid' => '3431',
      'name' => '农林牧渔',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3431',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3432 => 
    array (
      'linkageid' => '3432',
      'name' => '新闻门户',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3432',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3433 => 
    array (
      'linkageid' => '3433',
      'name' => '政府组织',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3433',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3434 => 
    array (
      'linkageid' => '3434',
      'name' => '论坛其它',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3434',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3435 => 
    array (
      'linkageid' => '3435',
      'name' => '博客',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3435',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3436 => 
    array (
      'linkageid' => '3436',
      'name' => '微博',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3436',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3437 => 
    array (
      'linkageid' => '3437',
      'name' => 'IT论坛',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3437',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3438 => 
    array (
      'linkageid' => '3438',
      'name' => '汽车论坛',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3438',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3439 => 
    array (
      'linkageid' => '3439',
      'name' => '教育论坛',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3439',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3440 => 
    array (
      'linkageid' => '3440',
      'name' => '军事论坛',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3440',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3441 => 
    array (
      'linkageid' => '3441',
      'name' => '体育论坛',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3441',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3442 => 
    array (
      'linkageid' => '3442',
      'name' => '旅游论坛',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3442',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3443 => 
    array (
      'linkageid' => '3443',
      'name' => '经济论坛',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3443',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3444 => 
    array (
      'linkageid' => '3444',
      'name' => '综合论坛',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3444',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3445 => 
    array (
      'linkageid' => '3445',
      'name' => '其他',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3445',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>