<?php
return array (
  63 => 
  array (
    'id' => '63',
    'catid' => '23',
    'typeid' => '0',
    'title' => '房地产行业一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/RealEstate/ztCasesFdc1.gif',
    'keywords' => '房地产 行业 一',
    'description' => '房地产行业一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/RealEstate/23-63-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406740',
    'updatetime' => '1358502669',
    'hitsid' => 'c-1-63',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  64 => 
  array (
    'id' => '64',
    'catid' => '23',
    'typeid' => '0',
    'title' => '房地产行业二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/RealEstate/ztCasesFdc2.gif',
    'keywords' => '房地产 行业 二',
    'description' => '房地产行业二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/RealEstate/23-64-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406780',
    'updatetime' => '1358503833',
    'hitsid' => 'c-1-64',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  65 => 
  array (
    'id' => '65',
    'catid' => '23',
    'typeid' => '0',
    'title' => '房地产行业三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/RealEstate/ztCasesFdc3.gif',
    'keywords' => '房地产 行业 三',
    'description' => '房地产行业三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/RealEstate/23-65-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406800',
    'updatetime' => '1358406818',
    'hitsid' => 'c-1-65',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  66 => 
  array (
    'id' => '66',
    'catid' => '23',
    'typeid' => '0',
    'title' => '房地产行业四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/RealEstate/ztCasesFdc4.gif',
    'keywords' => '房地产 行业 四',
    'description' => '房地产行业四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/RealEstate/23-66-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406820',
    'updatetime' => '1358406839',
    'hitsid' => 'c-1-66',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  67 => 
  array (
    'id' => '67',
    'catid' => '23',
    'typeid' => '0',
    'title' => '房地产行业五',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/RealEstate/ztCasesFdc5.gif',
    'keywords' => '房地产 行业 五',
    'description' => '房地产行业五',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/RealEstate/23-67-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406843',
    'updatetime' => '1358406868',
    'hitsid' => 'c-1-67',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  68 => 
  array (
    'id' => '68',
    'catid' => '23',
    'typeid' => '0',
    'title' => '房地产行业六',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/RealEstate/ztCasesFdc6.gif',
    'keywords' => '房地产 行业 六',
    'description' => '房地产行业六',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/RealEstate/23-68-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406870',
    'updatetime' => '1358406891',
    'hitsid' => 'c-1-68',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>