<?php
return array (
  62 => 
  array (
    'id' => '62',
    'catid' => '22',
    'typeid' => '0',
    'title' => '旅游行业五',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Travel/ztCasesly5.gif',
    'keywords' => '旅游行业 五',
    'description' => '旅游行业五',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Travel/22-62-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406714',
    'updatetime' => '1358502110',
    'hitsid' => 'c-1-62',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  61 => 
  array (
    'id' => '61',
    'catid' => '22',
    'typeid' => '0',
    'title' => '旅游行业四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Travel/ztCasesly4.gif',
    'keywords' => '旅游行业 四',
    'description' => '旅游行业四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Travel/22-61-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406693',
    'updatetime' => '1359363060',
    'hitsid' => 'c-1-61',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
  59 => 
  array (
    'id' => '59',
    'catid' => '22',
    'typeid' => '0',
    'title' => '旅游行业二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Travel/ztCasesly2.gif',
    'keywords' => '旅游行业 二',
    'description' => '旅游行业二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Travel/22-59-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406650',
    'updatetime' => '1358502147',
    'hitsid' => 'c-1-59',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  60 => 
  array (
    'id' => '60',
    'catid' => '22',
    'typeid' => '0',
    'title' => '旅游行业三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Travel/ztCasesly3.gif',
    'keywords' => '旅游行业 三',
    'description' => '旅游行业三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Travel/22-60-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406672',
    'updatetime' => '1358502146',
    'hitsid' => 'c-1-60',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  58 => 
  array (
    'id' => '58',
    'catid' => '22',
    'typeid' => '0',
    'title' => '旅游行业一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Travel/ztCasesly1.gif',
    'keywords' => '旅游行业 一',
    'description' => '旅游行业一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Travel/22-58-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406627',
    'updatetime' => '1358406648',
    'hitsid' => 'c-1-58',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>