<?php
return array (
  69 => 
  array (
    'id' => '69',
    'catid' => '24',
    'typeid' => '0',
    'title' => '教育行业一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Train/ztCasesFdc1.gif',
    'keywords' => '教育 行业 一',
    'description' => '教育行业一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Train/24-69-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406902',
    'updatetime' => '1358406929',
    'hitsid' => 'c-1-69',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  70 => 
  array (
    'id' => '70',
    'catid' => '24',
    'typeid' => '0',
    'title' => '教育行业二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Train/ztCasesFdc2.gif',
    'keywords' => '教育 行业 二',
    'description' => '教育行业二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Train/24-70-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406931',
    'updatetime' => '1358406948',
    'hitsid' => 'c-1-70',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  71 => 
  array (
    'id' => '71',
    'catid' => '24',
    'typeid' => '0',
    'title' => '教育行业三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Train/ztCasesFdc3.gif',
    'keywords' => '教育 行业 三',
    'description' => '教育行业三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Train/24-71-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406950',
    'updatetime' => '1358406971',
    'hitsid' => 'c-1-71',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  72 => 
  array (
    'id' => '72',
    'catid' => '24',
    'typeid' => '0',
    'title' => '教育行业四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Train/ztCasesFdc4.gif',
    'keywords' => '教育 行业 四',
    'description' => '教育行业四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Train/24-72-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406973',
    'updatetime' => '1358406990',
    'hitsid' => 'c-1-72',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>