<?php
return array (
  73 => 
  array (
    'id' => '73',
    'catid' => '25',
    'typeid' => '0',
    'title' => '汽车行业一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/AutoAccessories/ztCasesQc1.gif',
    'keywords' => '汽车行业 一',
    'description' => '汽车行业一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Auto/25-73-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407001',
    'updatetime' => '1358407021',
    'hitsid' => 'c-1-73',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  74 => 
  array (
    'id' => '74',
    'catid' => '25',
    'typeid' => '0',
    'title' => '汽车行业二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/AutoAccessories/ztCasesQc2.gif',
    'keywords' => '汽车行业 二',
    'description' => '汽车行业二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Auto/25-74-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407023',
    'updatetime' => '1358407039',
    'hitsid' => 'c-1-74',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  75 => 
  array (
    'id' => '75',
    'catid' => '25',
    'typeid' => '0',
    'title' => '汽车行业三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/AutoAccessories/ztCasesQc3.gif',
    'keywords' => '汽车行业 三',
    'description' => '汽车行业三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Auto/25-75-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407042',
    'updatetime' => '1358407062',
    'hitsid' => 'c-1-75',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  76 => 
  array (
    'id' => '76',
    'catid' => '25',
    'typeid' => '0',
    'title' => '汽车行业四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/AutoAccessories/ztCasesQc4.gif',
    'keywords' => '汽车行业 四',
    'description' => '汽车行业四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Auto/25-76-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407064',
    'updatetime' => '1358407085',
    'hitsid' => 'c-1-76',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  77 => 
  array (
    'id' => '77',
    'catid' => '25',
    'typeid' => '0',
    'title' => '汽车行业五',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/AutoAccessories/ztCasesQc5.gif',
    'keywords' => '汽车行业 五',
    'description' => '汽车行业五',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Auto/25-77-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407087',
    'updatetime' => '1358407107',
    'hitsid' => 'c-1-77',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>