<?php
return array (
  53 => 
  array (
    'id' => '53',
    'catid' => '21',
    'typeid' => '0',
    'title' => '餐饮行业一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Catering/ztCases1.gif',
    'keywords' => '餐饮行业 一',
    'description' => '餐饮行业一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Catering/21-53-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358405722',
    'updatetime' => '1358503280',
    'hitsid' => 'c-1-53',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  56 => 
  array (
    'id' => '56',
    'catid' => '21',
    'typeid' => '0',
    'title' => '餐饮行业四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Catering/ztCases4.gif',
    'keywords' => '餐饮行业 四',
    'description' => '餐饮行业四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Catering/21-56-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358405952',
    'updatetime' => '1358502198',
    'hitsid' => 'c-1-56',
    'views' => '3',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  54 => 
  array (
    'id' => '54',
    'catid' => '21',
    'typeid' => '0',
    'title' => '餐饮行业二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Catering/ztCases2.gif',
    'keywords' => '餐饮行业 二',
    'description' => '餐饮行业二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Catering/21-54-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358405864',
    'updatetime' => '1358502200',
    'hitsid' => 'c-1-54',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  55 => 
  array (
    'id' => '55',
    'catid' => '21',
    'typeid' => '0',
    'title' => '餐饮行业三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Catering/ztCases3.gif',
    'keywords' => '餐饮行业三',
    'description' => '餐饮行业三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Catering/21-55-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358405904',
    'updatetime' => '1358502202',
    'hitsid' => 'c-1-55',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  57 => 
  array (
    'id' => '57',
    'catid' => '21',
    'typeid' => '0',
    'title' => '餐饮行业五',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Catering/ztCases5.gif',
    'keywords' => '餐饮行业 五',
    'description' => '餐饮行业五',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Catering/21-57-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358406496',
    'updatetime' => '1358502196',
    'hitsid' => 'c-1-57',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>