<?php
return array (
  84 => 
  array (
    'id' => '84',
    'catid' => '27',
    'typeid' => '0',
    'title' => '律所行业一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/LawFirm/ztCasesLs1.gif',
    'keywords' => '律 所 行业',
    'description' => '律所行业一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/LawFirm/27-84-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409261',
    'updatetime' => '1358560913',
    'hitsid' => 'c-1-84',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  89 => 
  array (
    'id' => '89',
    'catid' => '27',
    'typeid' => '0',
    'title' => '律所行业六',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/LawFirm/ztCasesLs6.gif',
    'keywords' => '律 所 行业',
    'description' => '律所行业六',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/LawFirm/27-89-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409373',
    'updatetime' => '1358560926',
    'hitsid' => 'c-1-89',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  85 => 
  array (
    'id' => '85',
    'catid' => '27',
    'typeid' => '0',
    'title' => '律所行业二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/LawFirm/ztCasesLs2.gif',
    'keywords' => '律 所 行业',
    'description' => '律所行业二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/LawFirm/27-85-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409293',
    'updatetime' => '1358409314',
    'hitsid' => 'c-1-85',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  86 => 
  array (
    'id' => '86',
    'catid' => '27',
    'typeid' => '0',
    'title' => '律所行业三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/LawFirm/ztCasesLs3.gif',
    'keywords' => '律 所 行业',
    'description' => '律所行业三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/LawFirm/27-86-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409316',
    'updatetime' => '1358409334',
    'hitsid' => 'c-1-86',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  87 => 
  array (
    'id' => '87',
    'catid' => '27',
    'typeid' => '0',
    'title' => '律所行业四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/LawFirm/ztCasesLs4.gif',
    'keywords' => '律 所 行业',
    'description' => '律所行业四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/LawFirm/27-87-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409336',
    'updatetime' => '1358409353',
    'hitsid' => 'c-1-87',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  88 => 
  array (
    'id' => '88',
    'catid' => '27',
    'typeid' => '0',
    'title' => '律所行业五',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/LawFirm/ztCasesLs5.gif',
    'keywords' => '律 所 行业',
    'description' => '律所行业五',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/LawFirm/27-88-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409355',
    'updatetime' => '1358409371',
    'hitsid' => 'c-1-88',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>