<?php
return array (
  94 => 
  array (
    'id' => '94',
    'catid' => '29',
    'typeid' => '0',
    'title' => '服装行业一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Clothing/fzCase1.jpg',
    'keywords' => '服装行业 一',
    'description' => '服装行业一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Clothing/29-94-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409491',
    'updatetime' => '1358477041',
    'hitsid' => 'c-1-94',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  95 => 
  array (
    'id' => '95',
    'catid' => '29',
    'typeid' => '0',
    'title' => '服装行业二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Clothing/fzCase2.jpg',
    'keywords' => '服装行业 二',
    'description' => '服装行业二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Clothing/29-95-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409518',
    'updatetime' => '1358409537',
    'hitsid' => 'c-1-95',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  96 => 
  array (
    'id' => '96',
    'catid' => '29',
    'typeid' => '0',
    'title' => '服装行业三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Clothing/fzCase3.jpg',
    'keywords' => '服装行业 三',
    'description' => '服装行业三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Clothing/29-96-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409539',
    'updatetime' => '1358409563',
    'hitsid' => 'c-1-96',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  97 => 
  array (
    'id' => '97',
    'catid' => '29',
    'typeid' => '0',
    'title' => '服装行业四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Clothing/fzCase4.jpg',
    'keywords' => '服装行业 四',
    'description' => '服装行业四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Clothing/29-97-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409565',
    'updatetime' => '1358409582',
    'hitsid' => 'c-1-97',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  98 => 
  array (
    'id' => '98',
    'catid' => '29',
    'typeid' => '0',
    'title' => '服装行业五',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Clothing/fzCase5.jpg',
    'keywords' => '服装行业 五',
    'description' => '服装行业五',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Clothing/29-98-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409584',
    'updatetime' => '1358409602',
    'hitsid' => 'c-1-98',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  99 => 
  array (
    'id' => '99',
    'catid' => '29',
    'typeid' => '0',
    'title' => '服装行业六',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Clothing/fzCase6.jpg',
    'keywords' => '服装行业 六',
    'description' => '服装行业六',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Clothing/29-99-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409604',
    'updatetime' => '1358409640',
    'hitsid' => 'c-1-99',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>