<?php
return array (
  90 => 
  array (
    'id' => '90',
    'catid' => '28',
    'typeid' => '0',
    'title' => '管理咨询一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Management/ztCasesGl1.gif',
    'keywords' => '管理咨询 一',
    'description' => '管理咨询一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Management/28-90-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409400',
    'updatetime' => '1359421198',
    'hitsid' => 'c-1-90',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  93 => 
  array (
    'id' => '93',
    'catid' => '28',
    'typeid' => '0',
    'title' => '管理咨询四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Management/ztCasesGl4.gif',
    'keywords' => '管理咨询 四',
    'description' => '管理咨询四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Management/28-93-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409459',
    'updatetime' => '1359370044',
    'hitsid' => 'c-1-93',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  91 => 
  array (
    'id' => '91',
    'catid' => '28',
    'typeid' => '0',
    'title' => '管理咨询二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Management/ztCasesGl2.gif',
    'keywords' => '管理咨询 二',
    'description' => '管理咨询二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Management/28-91-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409422',
    'updatetime' => '1358409439',
    'hitsid' => 'c-1-91',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  92 => 
  array (
    'id' => '92',
    'catid' => '28',
    'typeid' => '0',
    'title' => '管理咨询三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Management/ztCasesGl3.gif',
    'keywords' => '管理咨询 三',
    'description' => '管理咨询三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Management/28-92-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358409441',
    'updatetime' => '1358409457',
    'hitsid' => 'c-1-92',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>