<?php
return array (
  78 => 
  array (
    'id' => '78',
    'catid' => '26',
    'typeid' => '0',
    'title' => '电子产品一',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Electronic/ztCasesDz1.gif',
    'keywords' => '电子产品 一',
    'description' => '电子产品一',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Electronic/26-78-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407118',
    'updatetime' => '1358502164',
    'hitsid' => 'c-1-78',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  79 => 
  array (
    'id' => '79',
    'catid' => '26',
    'typeid' => '0',
    'title' => '电子产品二',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Electronic/ztCasesDz2.gif',
    'keywords' => '电子产品 二',
    'description' => '电子产品二',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Electronic/26-79-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407145',
    'updatetime' => '1358502167',
    'hitsid' => 'c-1-79',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  80 => 
  array (
    'id' => '80',
    'catid' => '26',
    'typeid' => '0',
    'title' => '电子产品三',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Electronic/ztCasesDz3.gif',
    'keywords' => '电子产品 三',
    'description' => '电子产品三',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Electronic/26-80-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407165',
    'updatetime' => '1358502168',
    'hitsid' => 'c-1-80',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  81 => 
  array (
    'id' => '81',
    'catid' => '26',
    'typeid' => '0',
    'title' => '电子产品四',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Electronic/ztCasesDz4.gif',
    'keywords' => '电子产品 四',
    'description' => '电子产品四',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Electronic/26-81-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407184',
    'updatetime' => '1358502175',
    'hitsid' => 'c-1-81',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  82 => 
  array (
    'id' => '82',
    'catid' => '26',
    'typeid' => '0',
    'title' => '电子产品五',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Electronic/ztCasesDz5.gif',
    'keywords' => '电子产品 五',
    'description' => '电子产品五',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Electronic/26-82-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407204',
    'updatetime' => '1358407222',
    'hitsid' => 'c-1-82',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  83 => 
  array (
    'id' => '83',
    'catid' => '26',
    'typeid' => '0',
    'title' => '电子产品六',
    'style' => '',
    'thumb' => 'http://hy.30ie.com/uploadfile/Electronic/ztCasesDz6.gif',
    'keywords' => '电子产品 六',
    'description' => '电子产品六',
    'posids' => '0',
    'url' => 'http://localhost.hy30ie.com/html/Electronic/26-83-1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1358407224',
    'updatetime' => '1358407242',
    'hitsid' => 'c-1-83',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>